import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mercaluz",
  description: "Generated by create next app",
  icons: "/logo.svg",
};
import { Open_Sans } from "next/font/google";

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable}`}>
      <body className={`antialiased `}>{children}</body>
    </html>
  );
}
