import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mercaluz",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
